name: Build and publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./scripts
    shell: pwsh

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: |
          ./build.ps1
      - name: Publish
        if: github.actor != 'dependabot[bot]'
        env:
          GITHUBPAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./publish.ps1
